Sprint 2
Damir92/middle.messenger.praktikum.yandex pull request #2
Opened 2021-11-17 09:20 UTC by Damir92

2021-11-18 13:29 UTC, ua9msn requested changes
Есть места для доработки

2021-11-18 13:29 UTC, ua9msn commented on src/utils/variables.scss
>  $red-2:         #ff2f2f;
Именовать цвета их именами безсмысленно. Лучше именовать по месту использования: `background: #FFF`

2021-11-18 13:29 UTC, ua9msn commented on src/utils/validation.ts
> +        return nameRegexp.test(value);
Почитайте https://habr.com/ru/post/431866/ Особенно п.17

2021-11-18 13:29 UTC, ua9msn commented on src/utils/validation.ts
> +};
Это не нужно испралять здесь, но на будущее и вообще, старайтесь избегать валидации на регекспах.

2021-11-18 13:29 UTC, ua9msn commented on src/utils/HTTPTransport.ts
> +        return `${result}${key}=${data[key]}${index < keys.length - 1 ? '&' : ''}`;
`${index < keys.length - 1 ? '&' : ''}` Выглядит плохо. Лучше вместо `reduce`  использовать `map( .... ).join('&')`

2021-11-18 13:29 UTC, ua9msn commented on src/utils/Block.ts
> +    }
Из за неправильного порядка вам приходится везде в `componentDidUpdate` окружать биндинг обработчиков в `setTimout` Это очень плохо. Сначала отрендерите, затем вызовите `componentDidUpdate` .

2021-11-18 13:29 UTC, ua9msn commented on src/utils/Block.ts
> +    }
Почему бы не назвать функцию `getElement` ?  Название не соответствует содержимому

2021-11-18 14:05 UTC, Damir92 commented on src/utils/validation.ts
> +};
А какие еще есть варианты разбора строк для валидации?

2021-11-18 14:06 UTC, Damir92 commented
И еще вопрос, что не так со сборкой что переход по страницам не работает должным образом? 
js подгружается, но не исполняется

2021-11-18 14:14 UTC, ua9msn commented on src/utils/validation.ts
> +};
А зачем их вообще валидировать? Достаточно проверять длину. 
Для телефона только +- и цифры, тут да, регексп. Но и то, есть библиотека google-phone и она весьма не проста.
Я приму это сейчас, но в реальной работе я бы это зарубил.

2021-11-18 14:15 UTC, ua9msn commented
> И еще вопрос, что не так со сборкой что переход по страницам не работает должным образом? js подгружается, но не исполняется
У вас тип неправильный mime приходит. Смотрите заголовки сервера

2021-11-19 10:44 UTC, ua9msn commented on src/utils/HTTPTransport.ts
> +    return `?${keys.map(key => `${key}=${data[key]}`).join('&')}`;
Лучше так `return '?' +  keys.map( key => ``${key}=${data[key]}`` ).join('&')`

2021-12-13 05:11 UTC, merged

2022-03-17 15:56 UTC, ua9msn reviewed
Отличная работа. Принято

2022-03-17 15:56 UTC, ua9msn commented on src/modules/form/form.ts
> +        return '';
Обычно такие вещи сокращают до тренарного выражения 
` return (!!this.props.template) ? trueResult : falseResult` 
Это не ошибка

2022-03-17 15:56 UTC, ua9msn commented on src/pages/chats/chats.scss
> +}
Скрываете скроллбар но оставляете возможность скроллить? Просто любопытно зачем.

2022-03-17 15:56 UTC, ua9msn commented on src/pages/profile/modules/profile-form/profile-form.ts
> +            return item.includes('password')
Вообще то у поля password должен быть тип password. Почму вы проверяете именно className?